### ISSUE TITLE
maximum operating voltage

### ISSUE THREAD

**Issue by frankhommes** [maxl95/RGBW-Controller#1]
Hey,
I don't know how to contact you otherwise.
Is the operating Voltage really just 12 Volt? Because the linked mini360 says 4,75-23V to 1-17V. I'm asking because I wanne use your design for some boards with 24 Volt Power.

Thanks for your project which might help me a lot because Tasmota devices are not easily found anymore!
Frank

**Comment by maxl95** [comment]
Hey Frank,
thank you for your interest in my project. The maximum operating voltage is limited by the mini360 step-down. 
Since the specified operating voltage of the mini360 is 23V, I specified 12V. 
Unfortunately, I didn't have the time to test whether the step-down can withstand 24V.
I would be happy if you would report on your experiences here.

Regards Maximilian
